// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JMheUsxP1_6OVA1U9CYtc0BTNZqC-4U',
    appId: '1:300614073343:web:883aa33b9fd2de284885ca',
    messagingSenderId: '300614073343',
    projectId: 'homework-crud-ec848',
    authDomain: 'homework-crud-ec848.firebaseapp.com',
    storageBucket: 'homework-crud-ec848.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgaVudBw81yVNb0KUoO5JaS-y1GFLdYwQ',
    appId: '1:300614073343:android:c1cc7c62897335004885ca',
    messagingSenderId: '300614073343',
    projectId: 'homework-crud-ec848',
    storageBucket: 'homework-crud-ec848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehf0kPeKeKTnOmbqMoAlSe9uyYklfxsg',
    appId: '1:300614073343:ios:c259b660f7b11b5e4885ca',
    messagingSenderId: '300614073343',
    projectId: 'homework-crud-ec848',
    storageBucket: 'homework-crud-ec848.appspot.com',
    iosClientId: '300614073343-fb3hcf59tqe9jvdikl153ppgdtncgtg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeworkCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehf0kPeKeKTnOmbqMoAlSe9uyYklfxsg',
    appId: '1:300614073343:ios:c259b660f7b11b5e4885ca',
    messagingSenderId: '300614073343',
    projectId: 'homework-crud-ec848',
    storageBucket: 'homework-crud-ec848.appspot.com',
    iosClientId: '300614073343-fb3hcf59tqe9jvdikl153ppgdtncgtg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeworkCrud',
  );
}
